FROM debian:bullseye

RUN apt-get update && apt-get install -y \
    build-essential \
    libncurses5-dev \
    libncursesw5-dev

WORKDIR /app

COPY . .

# 這行是關鍵：建立 build 目錄
RUN mkdir -p build

RUN make

EXPOSE 8888

CMD ["./build/server"]

